# Generated by Django 3.2.11 on 2022-01-26 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLinkGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(default='74ae83aa021143c4a69c43dd1429d5a5', max_length=64)),
                ('alive_time', models.IntegerField(default=60, verbose_name='Время жизни ссылки(дни)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/uploads/users/avatars/default.png', upload_to='images/uploads/users/photo/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gifts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-10)], verbose_name='Дары'),
        ),
    ]
