# Generated by Django 4.0.1 on 2022-01-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220126_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='89434ad1cc7141619a64140e0ed18d7e', editable=False, max_length=64),
        ),
    ]
