# Generated by Django 4.0.1 on 2022-01-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_registrationlinkgenerator_url_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Пользователь не написал о себе.', max_length=1200),
        ),
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='d485d3519889449da8ea6c6c9f0cc734', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='abilities',
            field=models.ManyToManyField(to='account.Ability'),
        ),
    ]
